import { Field } from "../models/fieldModels";

export const ATTENDACE_FIELD: Field[] = [
  {
    name: "id",
    type: "singletext",
    description: `sdsdsdsdsds`,
    label: "Id",
    category: "Information",
    subcategory: "unique",
    similarHeaders: ["_id", "id"],
    required: true,
    option: [],
  },
  {
    name: "ticketno",
    type: "singletext",
    label: "Ticket No",
    subcategory: "unique",
    description: `sdsdsdsdds`,
    category: "Information",

    option: [],
  },
  {
    name: "fullname",
    type: "singletext",
    label: "Full Name",
    description: `dsdsdsdssdsd`,
    category: "Information",
    subcategory: "required",
    similarHeaders: ["name", "fullname", "fname", "full name", "full_name"],
    option: [],
  },
  {
    name: "codename",
    type: "singletext",
    label: "Code Name",
    description: `asasasas`,
    category: "Information",
    subcategory: "normal",
    similarHeaders: ["codename", "code name", "code_name"],
    option: [],
  },
  {
    name: "firstname",
    type: "singletext",
    label: "First Name",
    description: `required`,
    category: "Information",
    subcategory: "required",
    similarHeaders: ["fname", "first name", "first_name"],
    option: [],
  },
  {
    name: "lastname",
    type: "singletext",
    label: "Last Name",
    description: ``,
    category: "Information",
    subcategory: "required",
    similarHeaders: ["lname", "last name", "last_name"],
    option: [],
  },
  {
    name: "middlename",
    type: "singletext",
    label: "Middle Name",
    description: ``,
    category: "Information",
    subcategory: "normal",
    similarHeaders: ["mname", "middle name", "middle_name"],
    option: [],
  },
  {
    name: "middleinitial",
    type: "singletext",
    label: "Middle Initial",
    description: ``,
    category: "Information",
    subcategory: "normal",
    similarHeaders: [
      "mname",
      "middle name",
      "middle_name",
      "m_initial",
      "m.i.",
      "mi",
    ],
    option: [],
  },
  {
    name: "suffix",
    type: "singletext",
    label: "Suffix",
    description: ``,
    category: "Information",
    subcategory: "normal",
    similarHeaders: ["suffix", "suff"],
    option: [],
  },
  {
    name: "rank",
    type: "singletext",
    label: "Rank",
    description: ``,
    category: "Information",
    subcategory: "normal",
    similarHeaders: ["rank", "r"],
    option: [],
  },
  {
    name: "group",
    type: "multiselect",
    label: "Group",
    description: ``,
    category: "Group",
    subcategory: "normal",
    similarHeaders: ["group"],
    option: [],
  },
  {
    name: "status",
    type: "singleselect",
    label: "Status",
    description: ``,
    category: "Activity",
    subcategory: "normal",
    similarHeaders: ["status"],
    option: [],
  },
  {
    name: "location",
    type: "object",
    label: "Location",
    description: ``,
    category: "Information",
    subcategory: "normal",
    option: [],
  },

  {
    name: "timein",
    type: "time",
    label: "Time In",
    description: ``,
    category: "Activity",
    subcategory: "normal",
    similarHeaders: ["timein"],
    option: [],
  },
  {
    name: "timeout",
    type: "time",
    label: "Time Out",
    description: ``,
    category: "Activity",
    subcategory: "normal",
    similarHeaders: ["timeout"],
    option: [],
  },
  {
    name: "date",
    type: "date",
    label: "Date",
    description: ``,
    category: "History",
    subcategory: "normal",
    similarHeaders: ["date"],
    option: [],
  },
  {
    name: "duration",
    type: "calculated",
    label: "Duration",
    description: ``,
    category: "History",
    subcategory: "normal",
    similarHeaders: ["duration"],
    option: [],
  },
  {
    name: "notes",
    type: "multitext",
    label: "Notes",
    description: ``,
    category: "Other",
    subcategory: "normal",
    similarHeaders: ["notes"],
    option: [],
  },
  {
    name: "certificate",
    type: "app",
    label: "Generate Certificate",
    description: ``,
    category: "Apps",
    subcategory: "normal",
    similarHeaders: [],
    option: [],
  },
  {
    name: "id",
    type: "app",
    label: "Generate ID",
    description: ``,
    category: "Apps",
    subcategory: "normal",
    similarHeaders: [],
    option: [],
  },
];
